project_id = "cocieziwytadhzcktqhf"

[functions.track-share-view]
verify_jwt = false

[functions.capture-website-screenshot]
verify_jwt = false

[functions.discover-logo]
verify_jwt = false

[functions.run-psi]
verify_jwt = false

[functions.run-psi-and-update]
verify_jwt = false